import datetime
from typing import Callable


class PatternCollector:
    """Collects patterns for feature extraction.

    Attributes:
        chars (list): List of special characters to count in URLs.
        short_domains (list): List of short domain patterns to check in URLs.
    """

    chars = [
        '!', '@', '#', '$', '%',
        '^', '&', '*', '(', ')',
        '{', '}', '[', ']', '~',
        '`', ':', ';', '|', '\\',
        ',', '.', '<', '>', '?',
        '/', '+', '=', '-', '_',
        "'", '"'
    ]
    short_domains = [
        'bit.ly', 'goo.gl', 'tinyurl.com', 't.co', 'ow.ly', 'is.gd', 'shorte.st', 'adf.ly',
        'bc.vc', 'cli.gs', 'cutt.us', 'u.to', 'j.mp', 'v.gd', 'qr.ae', 'tr.im', 'prettylinkpro.com',
        'yourls.org', 'slink.be', 'scrnch.me', 'filoops.info', 'vzturl.com', 'x.co', 'zzb.bz',
        '1url.com', 'tweez.me', 'v.tl', 'lnkd.in', 'dft.ba', 'yep.it', 'hurl.me', 'url.ie',
        'link.zip.net', 'cort.as', 'po.st', '4sq.com', '1u.bb', 'awk.fr', 'buzurl.com', 'cutt.ly',
        't2m.io', 'waa.ai', 'get.shorty', 'tiny.cc', 'short.to', 'snip.ly', 'pt.link', 'cl.lk',
        'soo.gd', 'ity.im', 'yfrog.com', 'twitthis.com', 'u.nu', 'plurl.me', 'urlx.ie', 'poprl.com',
        'to.ly', 'bit.do', 'rb.gy', 'shorturl.at', 'clicky.me', 'budurl.com', 'trim.li', 'qr.net',
        'url.kz', 'ur2.me', '2.tu', 'zpag.es', 'xlink.me', 'goshrink.com', 'picz.us', 'tinyarrows.net',
        'chilp.it', 'nanoref.com', 'notlong.com', 'post.ly', 'xrl.us', 'url4.eu', 'virl.ws', 'migre.me',
        'buk.me', 'cuturls.com', 'fun.ly', 'snipurl.com', 'golinks.co', 'viralurl.biz', 'twurl.nl', 'merky.de'
    ]

    top_100_urls = [
        "https://www.google.com",
        "https://www.facebook.com",
        "https://www.youtube.com",
        "https://www.wp.pl",
        "https://www.google.pl",
        "https://www.onet.pl",
        "https://www.allegro.pl",
        "https://www.interia.pl",
        "https://www.wikipedia.org",
        "https://www.olx.pl",
        "https://www.gazeta.pl",
        "https://www.o2.pl",
        "https://www.instagram.com",
        "https://www.pornhub.com",
        "https://www.ceneo.pl",
        "https://www.tvn24.pl",
        "https://www.pudelek.pl",
        "https://www.cda.pl",
        "https://www.netflix.com",
        "https://www.librus.pl",
        "https://www.wyborcza.pl",
        "https://www.money.pl",
        "https://www.otomoto.pl",
        "https://www.twitter.com",
        "https://www.filmweb.pl",
        "https://www.wykop.pl",
        "https://www.fakt.pl",
        "https://www.sport.onet.pl",
        "https://www.businessinsider.com.pl",
        "https://www.sport.pl",
        "https://www.ipko.pl",
        "https://www.medonet.pl",
        "https://www.xvideos.com",
        "https://www.se.pl",
        "https://www.vulcan.net.pl",
        "https://www.xnxx.com",
        "https://www.radiozet.pl",
        "https://www.naszemiasto.pl",
        "https://www.google.com.br",
        "https://www.xhamster.com",
        "https://www.jbzd.com.pl",
        "https://www.plotek.pl",
        "https://www.tvp.pl",
        "https://www.pomponik.pl",
        "https://www.mbank.pl",
        "https://www.abczdrowie.pl",
        "https://www.plejada.pl",
        "https://www.flashscore.pl",
        "https://www.sport.interia.pl",
        "https://www.aliexpress.com",
        "https://www.demotywatory.pl",
        "https://www.onnetwork.tv",
        "https://www.pikio.pl",
        "https://www.ingbank.pl",
        "https://www.mediaexpert.pl",
        "https://www.joemonster.org",
        "https://www.poradnikzdrowie.pl",
        "https://www.otodom.pl",
        "https://www.messenger.com",
        "https://www.play.pl",
        "https://www.lotto.pl",
        "https://www.gemius.pl",
        "https://www.linkedin.com",
        "https://www.pepper.pl",
        "https://www.ing.pl",
        "https://www.booking.com",
        "https://www.centrum24.pl",
        "https://www.mp.pl",
        "https://www.dobreprogramy.pl",
        "https://www.pracuj.pl",
        "https://www.bankier.pl",
        "https://www.euro.com.pl",
        "https://www.pinterest.com",
        "https://www.twitch.tv",
        "https://www.redtube.com",
        "https://www.meczyki.pl",
        "https://www.zalando.pl",
        "https://www.plus.pl",
        "https://www.wprost.pl",
        "https://www.datezone.com",
        "https://www.poczta-polska.pl",
        "https://www.komputerswiat.pl",
        "https://www.finanse.wp.pl",
        "https://www.roksa.pl",
        "https://www.vod.pl",
        "https://www.telemagazyn.pl",
        "https://www.sprzedajemy.pl",
        "https://www.pekao24.pl",
        "https://www.t-mobile.pl",
        "https://www.gemius.com",
        "https://www.bongacams.com",
        "https://www.kwejk.pl",
        "https://www.yahoo.com",
        "https://www.elektroda.pl",
        "https://www.brainly.pl",
        "https://www.zalukaj.com",
        "https://www.orange.pl",
        "https://www.auto-swiat.pl",
        "https://www.meteo.pl",
        "https://www.doz.pl"
    ]





